/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Property = {
  _id: string;
  _type: "property";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  city?: "Calgary" | "Edmonton" | "Red Deer" | "Penhold" | "Sylvan Lake";
  address?: string;
  price?: number;
  pricePeriod?: "night" | "month";
  bedrooms?: number;
  bathrooms?: number;
  sqft?: number;
  guests?: number;
  availableDate?: string;
  availableNow?: boolean;
  isActive?: boolean;
  tag?: string;
  description?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  videoUrl?: string;
  videoPoster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  amenities?: Array<string>;
  idealFor?: Array<string>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Property
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../StayAlberta/src/sanity/queries.ts
// Variable: PROPERTIES_QUERY
// Query: *[_type == "property" && isActive != false] {    "id": _id,    title,    "slug": slug.current,    city,    address,    price,    pricePeriod,    bedrooms,    bathrooms,    sqft,    guests,    availableDate,    availableNow,    isActive,    tag,    description,    "images": images[].asset->url,    videoUrl,    "videoPoster": videoPoster.asset->url,    amenities,    idealFor  }
export type PROPERTIES_QUERY_RESULT = Array<{
  id: string;
  title: string | null;
  slug: string | null;
  city: "Calgary" | "Edmonton" | "Penhold" | "Red Deer" | "Sylvan Lake" | null;
  address: string | null;
  price: number | null;
  pricePeriod: "month" | "night" | null;
  bedrooms: number | null;
  bathrooms: number | null;
  sqft: number | null;
  guests: number | null;
  availableDate: string | null;
  availableNow: boolean | null;
  isActive: boolean | null;
  tag: string | null;
  description: string | null;
  images: Array<string | null> | null;
  videoUrl: string | null;
  videoPoster: string | null;
  amenities: Array<string> | null;
  idealFor: Array<string> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "property" && isActive != false] {\n    "id": _id,\n    title,\n    "slug": slug.current,\n    city,\n    address,\n    price,\n    pricePeriod,\n    bedrooms,\n    bathrooms,\n    sqft,\n    guests,\n    availableDate,\n    availableNow,\n    isActive,\n    tag,\n    description,\n    "images": images[].asset->url,\n    videoUrl,\n    "videoPoster": videoPoster.asset->url,\n    amenities,\n    idealFor\n  }\n': PROPERTIES_QUERY_RESULT;
  }
}
